#!/usr/bin/env python
# cb-opentiles:
# A script to allow for tiling window management with Openbox.
# Written for CrunchBang Linux <http://crunchbang.org/>
# by projektile
# ----------------------------------------------------------------------
# License:
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, October 2013
#
# Copyright (C) 2013 projektile <https://github.com/projektile>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.
# ----------------------------------------------------------------------

from subprocess import Popen, PIPE, STDOUT
import sys, os, subprocess, re

#history = ''  # '/tmp/opentiles-'+str(os.getuid())                                #later this can be moved and have desktop number appended

p = Popen(['xdotool','getdisplaygeometry'], stdout=PIPE, stderr=STDOUT)
Dimensions = p.communicate()
Dimensions = Dimensions[0].replace('\n', '')
Dimensions = Dimensions.split(' ')
res_width = int(Dimensions[0])
res_height = int(Dimensions[1])

p = Popen(['wmctrl', '-d'], stdout=PIPE, stderr=STDOUT)
desktop = p.communicate()
desktop = str(desktop)
i = 0
while i < len(desktop):
	if desktop[i] == "*":
		active_desktop = desktop[i-3]
		break
	else:
		i = i + 1

history = '/tmp/opentiles-'+str(os.getuid())+'-'+str(active_desktop)                             #trying this

windows_arr = []
method = 0
columns = 2
ID = 0

x_offset = 0
y_offset = 0
useless_gap = 21  #14
x_object = 0
y_object = 0

if os.path.exists(history) == False:                          #note this here.
	f = open(history,'w')
	f.close()

def print_usage():
	print "cb-opentiles: usage:"
	print "  --help     show this message and exit"
	print "  --left     tile two window columns"
	print "  --right    tile three window columns"
	print ""
	exit()

def window_id():
	p = Popen(['xdotool', 'getactivewindow'], stdout=PIPE)
	ID = p.communicate()
	ID = int(ID[0])
	p = Popen(['xdotool', 'getwindowpid', str(ID)], stdout=PIPE)
	PID = p.communicate()
	PID = int(PID[0])
	return str(ID)+'-'+str(PID)

def windows_store(windows):
	os.system('rm /tmp/opentiles-'+str(os.getuid())+'-'+str(active_desktop))
	s = str(x_offset) + ' \n'
	f = open(history,'a')
	f.write(s)
	for i in windows:
		s = i + ' \n'
		f = open(history,'a')
		f.write(s)
	f.close()

def history_lookup():
	global x_offset
	global y_offset
	f = open(history,'r')
	i = 0
	for line in f:
		print(line)
		if i == 0:
			xo = str(line)          #come back to this (may be able to set x_offset sooner)
			i = i + 1
		else:
			z = str(line[:10])
			if z in windows_arr:
				i = i + 1
			else:
				return False
	f.close()
	if i-1 == len(windows_arr):           #Make -2 when add y_offset
		x_offset = int(xo)
		return True
	else:
		return False

def windows_assign():
	f = open(history,'r')
	loaded_list = []
	i = 0
	for line in f:
		if (i != 0):
			z = str(line[:10])
			loaded_list.append(z)
		i = i + 1
	f.close()
	return loaded_list

def get_windows(desktop_num):
	p = Popen(['wmctrl', '-l', '-G'], stdout=PIPE, stderr=STDOUT)
	windows = p.communicate()
	windows = windows[0].replace('\n', ' \n')
	windows = windows.split('\n')
	tile_list = []
	for i in windows:
		if i[11:13] == " " + desktop_num:
			tile_list.append(i[:10])
	return tile_list

def panel_farside(dimension):
	p = Popen(['wmctrl', '-l', '-G'], stdout=PIPE, stderr=STDOUT)
	windows = p.communicate()
	windows = windows[0].replace('\n', ' \n')
	windows = windows.split('\n')
	panel_list = []
	for i in windows:
		if i[11:13] == "-1":
			panel_list.append(i[14:32])
	for i in panel_list:
		x = int(i[10:14].replace(' ',''))
		y = int(i[14:18].replace(' ',''))
		x_coord = int(i[:4].replace(' ',''))
		y_coord = int(i[4:8].replace(' ',''))
		if (dimension == "x") & (x < y):
			if x_coord > res_width/2:
				return True
			else:
				return False
		if (dimension =="y") & (x > y):
			if y_coord > res_height/2:
				return True
			else:
				return False
	return True

def tile_windows(windows, col):
	n = 0
	for i in windows:
		h_frac = int((res_width/columns)*(col-1)+(useless_gap*.5))
		v_frac = int((n*(res_height/len(windows)))+(useless_gap*.5))
		if panel_farside("x")==False:
			h_frac += x_object
		if panel_farside("y")==False:
			v_frac += y_object
		width = int((res_width/columns)-useless_gap)
		height = int(res_height/len(windows)-useless_gap)
		if col==1:
			width += x_offset
		else:
			width -= x_offset
			h_frac += x_offset
		dim_string = str(h_frac)+","+str(v_frac)+","+str(width)+","+str(height)
		os.system("xdotool windowactivate "+i)
		os.system("wmctrl -r :ACTIVE: -e 1,"+dim_string)
		n = n + 1

def factor_inactive(dimension):
	p = Popen(['wmctrl', '-l', '-G'], stdout=PIPE, stderr=STDOUT)
	windows = p.communicate()
	windows = windows[0].replace('\n', ' \n')
	windows = windows.split('\n')
	inactive_list = []
	for i in windows:
		if i[11:13] == "-1":
			inactive_list.append(i[24:32])
	for i in inactive_list:
		x = int(i[:4].replace(' ',''))
		y = int(i[4:8].replace(' ',''))
		if dimension == "x":
			if x < y:
				return x
		if dimension =="y":
			if x > y:
				return y
	return 0

def set_offset(windows_arr):                              #print_usage() needs to find a new home!
	global x_offset
	if "--left" in sys.argv:
		x_offset -= 75
	elif "--right" in sys.argv:
		x_offset += 75
	elif "--rotate" not in sys.argv:
		print_usage()

def rotate(list, x):
	return list[-x:] + list[:-x]

def sort_windows(windows_arr):
	if len(windows_arr) <= 4:
		tile_windows(windows_arr[:1],1)
		tile_windows(windows_arr[1:],2)
	else:
		window_sets = []*columns
		x = 0
		while x < columns:
			window_sets.append(windows_arr[x*(len(windows_arr)/2):((x+1)*(len(windows_arr)/2))+x])
			tile_windows(window_sets[x], x+1)
			x+=1

def main():
	global x_object
	global y_object
	global res_width
	global res_height
	global active_desktop
	global windows_arr
	global method
	global ID
	global x_offset
	global history
	x_object = int(factor_inactive("x"))
	y_object = int(factor_inactive("y"))
	res_width = res_width - x_object
	res_height = res_height - y_object
	windows_arr = get_windows(active_desktop)
	ID = window_id()
	if history_lookup():
		windows_arr = windows_assign()
		if "--rotate" in sys.argv:
			windows_arr = rotate(windows_arr, 1)
	set_offset(windows_arr)
	sort_windows(windows_arr)
	windows_store(windows_arr)
	os.system("xdotool windowactivate " + str(ID))

main()
